server:
  port: ${server.port}

management:
  server:
    port: ${management.port}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: false

info:
  damsel:
    version: ${damsel.version}
  stage: dev
  version: ${project.version}

spring:
  application:
    name: ${project.name}
  datasource:
    hikari:
      idle-timeout: 30000
      leak-detection-threshold: 60000
      data-source-properties:
        prepareThreshold: 0
      maximum-pool-size: 50
      max-lifetime: 300000
      minimum-idle: 2
    password: ${db.password}
    url: ${db.url}
    username: ${db.user}

db:
  jdbc:
    tr_timeout: 10000
